name: 🚀 Deploy Firefox Extension to AMO

on:
  release:
    types: [created]

jobs:
  upload:
    name: Upload to Mozilla Add-ons
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v2

      - name: 📦 Zip Extension
        run: |
          zip -r extension.zip . -x '*.git*' '*.github*' 'README.md'

      - name: 🚀 Upload to AMO
        uses: trmcnvn/firefox-addon@v1
        with:
          xpi: extension.zip
          jwtIssuer: ${{ secrets.AMO_JWT_ISSUER }}
          jwtSecret: ${{ secrets.AMO_JWT_SECRET }}
